const Cart=require("./Models/Cart")
const dotenv=require("dotenv")
const express=require("express")
const mongoose=require("mongoose")
const cors=require("cors")
const routes=require("./Routes/studentRoute")
const cart=require("./Routes/cartRoute")
const product=require("./Routes/productRoute")
const admin=require("./Routes/adminRoute")
const app=express()
app.use(express.json())
app.use(cors())
app.use("/user",routes)
app.use("/cart",cart)
app.use("/product",product)
app.use("/admin",admin)
dotenv.config()
mongoose.connect(process.env.MONGODB_URL)
.then(()=>console.log("Connected Successfully"))
.catch(error=>console.log(error.message))
app.listen(3000,()=>{
    console.log("Server running on port 3000");
    
})